/**
 * WorkForge AI Bug Fix Agent
 *
 * Pulls unresolved Sentry errors, uses Claude Opus to analyze and fix them,
 * then creates a GitHub PR (confidence >= 80) or issue (confidence 50-79).
 *
 * Required env: ANTHROPIC_API_KEY, SENTRY_AUTH_TOKEN, SENTRY_DSN, GITHUB_TOKEN, REPO
 */

import Anthropic from '@anthropic-ai/sdk'
import fs from 'fs'
import path from 'path'
import { execSync } from 'child_process'

const REPO = process.env.REPO // e.g. "PaulR-coder/WorkForge"
const CONFIDENCE_THRESHOLD = 80
const CONFIDENCE_ISSUE_MIN = 50
const MAX_ISSUES = 3
const MAX_AGENT_TURNS = 20

const anthropic = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY })

// ─── Sentry helpers ──────────────────────────────────────────────────────────

function parseDsn(dsn) {
  // https://<key>@o<orgId>.ingest.us.sentry.io/<projectId>
  const match = dsn.match(/https:\/\/[^@]+@o(\d+)\.ingest[^/]+\/(\d+)/)
  if (!match) throw new Error(`Cannot parse DSN: ${dsn}`)
  return { orgId: match[1], projectId: match[2] }
}

async function sentryGet(path) {
  const res = await fetch(`https://sentry.io/api/0${path}`, {
    headers: { Authorization: `Bearer ${process.env.SENTRY_AUTH_TOKEN}` },
  })
  if (!res.ok) {
    const body = await res.text()
    throw new Error(`Sentry ${res.status} ${path}: ${body.slice(0, 200)}`)
  }
  return res.json()
}

async function discoverSentrySlugs(orgId, projectId) {
  // Use numeric IDs directly — Sentry API accepts them
  // Verify by fetching org info
  const orgs = await sentryGet('/organizations/')
  const org = orgs.find(o => o.id === orgId) ?? orgs[0]
  if (!org) throw new Error('No Sentry organizations accessible with this token')

  const projects = await sentryGet(`/organizations/${org.slug}/projects/`)
  const project = projects.find(p => p.id === projectId) ?? projects[0]
  if (!project) throw new Error('No matching Sentry project found')

  return { orgSlug: org.slug, projectSlug: project.slug }
}

async function fetchIssues(orgSlug, projectSlug) {
  return sentryGet(
    `/projects/${orgSlug}/${projectSlug}/issues/?query=is:unresolved&limit=${MAX_ISSUES}&sort=date`,
  )
}

async function fetchLatestEvent(issueId) {
  return sentryGet(`/issues/${issueId}/events/latest/`)
}

function formatStackTrace(event) {
  const exception = event.entries?.find(e => e.type === 'exception')
  const frames = exception?.data?.values?.[0]?.stacktrace?.frames ?? []
  const appFrames = frames.filter(f => f.inApp || f.filename?.includes('src/'))

  if (!appFrames.length) return '(no app-level stack frames available)'

  return appFrames
    .map(f => {
      const ctx = f.context?.map(([, line]) => `    ${line}`).join('\n') ?? ''
      return `  ${f.filename}:${f.lineNo} in ${f.function ?? 'anonymous'}\n${ctx}`
    })
    .join('\n')
}

// ─── GitHub helpers ───────────────────────────────────────────────────────────

async function githubRequest(method, path, body) {
  const res = await fetch(`https://api.github.com${path}`, {
    method,
    headers: {
      Authorization: `Bearer ${process.env.GITHUB_TOKEN}`,
      'Content-Type': 'application/json',
      Accept: 'application/vnd.github+json',
      'X-GitHub-Api-Version': '2022-11-28',
    },
    ...(body ? { body: JSON.stringify(body) } : {}),
  })
  if (!res.ok) {
    const err = await res.text()
    throw new Error(`GitHub ${method} ${path} → ${res.status}: ${err.slice(0, 300)}`)
  }
  return res.json()
}

async function getMainSha() {
  const ref = await githubRequest('GET', `/repos/${REPO}/git/ref/heads/main`)
  return ref.object.sha
}

async function getOpenAIPRs() {
  const prs = await githubRequest('GET', `/repos/${REPO}/pulls?state=open&per_page=100`)
  return prs.filter(pr => pr.title.startsWith('🤖'))
}

async function createBranch(branchName, sha) {
  await githubRequest('POST', `/repos/${REPO}/git/refs`, {
    ref: `refs/heads/${branchName}`,
    sha,
  })
}

async function upsertFile(filePath, content, branch, commitMessage) {
  const encoded = Buffer.from(content).toString('base64')
  let existingSha
  try {
    const existing = await githubRequest(
      'GET',
      `/repos/${REPO}/contents/${filePath}?ref=${branch}`,
    )
    existingSha = existing.sha
  } catch {
    existingSha = undefined
  }

  await githubRequest('PUT', `/repos/${REPO}/contents/${filePath}`, {
    message: commitMessage,
    content: encoded,
    branch,
    ...(existingSha ? { sha: existingSha } : {}),
  })
}

async function createPR(sentryIssue, fix, branchName) {
  const pr = await githubRequest('POST', `/repos/${REPO}/pulls`, {
    title: `🤖 [AI Fix] ${fix.fix_description}`,
    body: `## AI-Generated Bug Fix

**Sentry Issue:** ${sentryIssue.title}
**Sentry URL:** ${sentryIssue.permalink ?? 'N/A'}
**Confidence:** ${fix.confidence}/100
**Files changed:** ${fix.files.map(f => `\`${f.path}\``).join(', ')}

## Root Cause
${fix.reasoning}

## Files Modified
${fix.files.map(f => `- \`${f.path}\``).join('\n')}

---
> Generated by WorkForge AI Bug Fix Agent (Claude Opus). Review carefully before merging — merging triggers an automatic Railway deploy.`,
    head: branchName,
    base: 'main',
  })

  // Best-effort label creation
  try {
    await githubRequest('POST', `/repos/${REPO}/issues/${pr.number}/labels`, {
      labels: ['ai-generated', 'bug'],
    })
  } catch { /* labels may not exist */ }

  return pr
}

async function createIssue(sentryIssue, title, analysis, confidence) {
  const issue = await githubRequest('POST', `/repos/${REPO}/issues`, {
    title: `🤖 [AI Analysis] ${title}`,
    body: `## AI Bug Analysis

**Sentry Issue:** ${sentryIssue.title}
**Sentry URL:** ${sentryIssue.permalink ?? 'N/A'}
**AI Confidence:** ${confidence}/100 *(below ${CONFIDENCE_THRESHOLD} threshold — flagged for human review)*

## Analysis
${analysis}

---
> Flagged by WorkForge AI Bug Fix Agent (Claude Opus). Manual fix required.`,
    labels: ['ai-generated', 'needs-review'],
  })
  return issue
}

// ─── File system tools (safe, sandboxed to cwd) ──────────────────────────────

const CWD = process.cwd()

function safePath(p) {
  const resolved = path.resolve(CWD, p)
  if (!resolved.startsWith(CWD)) throw new Error(`Path traversal blocked: ${p}`)
  return resolved
}

function toolReadFile(p) {
  try {
    return fs.readFileSync(safePath(p), 'utf8')
  } catch (e) {
    return `Error: ${e.message}`
  }
}

function toolListDir(p) {
  try {
    return fs
      .readdirSync(safePath(p), { withFileTypes: true })
      .map(e => `${e.isDirectory() ? '[dir] ' : '[file]'} ${e.name}`)
      .join('\n')
  } catch (e) {
    return `Error: ${e.message}`
  }
}

function toolSearchCode(query) {
  try {
    return (
      execSync(
        `grep -r --include="*.ts" --include="*.tsx" -l ${JSON.stringify(query)} src/ 2>/dev/null | head -20`,
        { encoding: 'utf8', cwd: CWD },
      ) || 'No matches'
    )
  } catch {
    return 'No matches'
  }
}

// ─── Claude tool definitions ──────────────────────────────────────────────────

const TOOLS = [
  {
    name: 'read_file',
    description: 'Read a source file from the repository.',
    input_schema: {
      type: 'object',
      properties: {
        path: { type: 'string', description: 'Relative path from repo root, e.g. src/app/api/jobs/route.ts' },
      },
      required: ['path'],
    },
  },
  {
    name: 'list_directory',
    description: 'List files and subdirectories at a path.',
    input_schema: {
      type: 'object',
      properties: {
        path: { type: 'string', description: 'Relative directory path, e.g. src/app/api' },
      },
      required: ['path'],
    },
  },
  {
    name: 'search_code',
    description: 'Grep for a string across all TypeScript files under src/.',
    input_schema: {
      type: 'object',
      properties: {
        query: { type: 'string', description: 'The search string' },
      },
      required: ['query'],
    },
  },
  {
    name: 'submit_fix',
    description:
      'Submit a code fix. Call this once you have identified the bug and written the corrected code. ' +
      'Use confidence >= 80 only when you are certain the fix is correct and complete.',
    input_schema: {
      type: 'object',
      properties: {
        confidence: {
          type: 'number',
          description:
            '0–100. 80+ = certain fix, will create a PR. 50–79 = plausible but unsure, creates a GitHub issue. <50 = skip.',
        },
        fix_description: {
          type: 'string',
          description: 'One-line PR/commit title, e.g. "fix: handle null techId in job assignment"',
        },
        reasoning: {
          type: 'string',
          description: 'Full explanation of root cause and why this fix resolves it.',
        },
        files: {
          type: 'array',
          description: 'Files to create or overwrite. Provide COMPLETE file content — not diffs.',
          items: {
            type: 'object',
            properties: {
              path: { type: 'string', description: 'Relative path from repo root' },
              content: { type: 'string', description: 'Complete new file content' },
            },
            required: ['path', 'content'],
          },
        },
      },
      required: ['confidence', 'fix_description', 'reasoning', 'files'],
    },
  },
  {
    name: 'flag_unfixable',
    description:
      'Call this when you cannot identify a confident fix — e.g. the error is in a third-party library, ' +
      'requires environment changes, or needs more context than you have.',
    input_schema: {
      type: 'object',
      properties: {
        reason: { type: 'string', description: 'Why you cannot fix this automatically' },
      },
      required: ['reason'],
    },
  },
]

const SYSTEM_PROMPT = `You are an autonomous bug-fixing agent for WorkForge, a multi-tenant field operations SaaS.

Stack: Next.js 16, Prisma v7 + PostgreSQL, Railway deployment, TypeScript throughout.

Key source layout:
- src/app/api/          — API route handlers
- src/app/(app)/        — authenticated UI pages
- src/lib/              — shared utilities (auth, prisma, permissions, email, rateLimit, migrations, seed, tenant)
- src/generated/prisma/ — generated Prisma client (DO NOT EDIT)
- prisma/schema.prisma  — DB schema (DO NOT EDIT)

Your process:
1. Read the stack trace carefully to identify the file and line
2. Read that file (and related files if needed) to understand context
3. Identify the root cause
4. Write a complete corrected file
5. Call submit_fix with your confidence score

Hard rules:
- NEVER modify: prisma/schema.prisma, src/lib/migrations.ts, src/generated/*, package.json, *.toml, *.env*
- Always read a file before deciding to change it
- submit_fix requires COMPLETE file content — not snippets or diffs
- Only change the minimum files needed
- If you cannot identify the bug with certainty, call flag_unfixable`

// ─── Main agent loop ──────────────────────────────────────────────────────────

async function runAgent(issue, event) {
  const stackTrace = formatStackTrace(event)

  const errorContext = [
    `Error: ${issue.title}`,
    `Culprit: ${issue.culprit ?? 'unknown'}`,
    `First seen: ${issue.firstSeen}`,
    `Last seen: ${issue.lastSeen}`,
    `Occurrence count: ${issue.count}`,
    ``,
    `Stack trace:`,
    stackTrace,
    event.message ? `\nMessage: ${event.message}` : '',
    event.contexts?.runtime ? `\nRuntime: ${JSON.stringify(event.contexts.runtime)}` : '',
  ]
    .filter(Boolean)
    .join('\n')

  const messages = [
    {
      role: 'user',
      content: `A Sentry error was detected in production. Investigate and fix it.\n\n${errorContext}`,
    },
  ]

  let fixResult = null
  let flagResult = null

  for (let turn = 0; turn < MAX_AGENT_TURNS; turn++) {
    const response = await anthropic.messages.create({
      model: 'claude-opus-4-7',
      max_tokens: 8000,
      system: SYSTEM_PROMPT,
      tools: TOOLS,
      messages,
    })

    messages.push({ role: 'assistant', content: response.content })

    if (response.stop_reason === 'end_turn') {
      console.log('  Agent finished without a tool decision')
      break
    }

    const toolUses = response.content.filter(b => b.type === 'tool_use')
    if (!toolUses.length) break

    const toolResults = []
    let done = false

    for (const use of toolUses) {
      let result

      if (use.name === 'read_file') {
        result = toolReadFile(use.input.path)
        console.log(`  read_file  ${use.input.path} (${result.length} chars)`)
      } else if (use.name === 'list_directory') {
        result = toolListDir(use.input.path)
        console.log(`  list_dir   ${use.input.path}`)
      } else if (use.name === 'search_code') {
        result = toolSearchCode(use.input.query)
        console.log(`  search     "${use.input.query}"`)
      } else if (use.name === 'submit_fix') {
        fixResult = use.input
        result = 'Fix received.'
        console.log(`  submit_fix confidence=${use.input.confidence} — ${use.input.fix_description}`)
        done = true
      } else if (use.name === 'flag_unfixable') {
        flagResult = use.input
        result = 'Noted.'
        console.log(`  flag_unfixable — ${use.input.reason}`)
        done = true
      }

      toolResults.push({ type: 'tool_result', tool_use_id: use.id, content: result })
      if (done) break
    }

    messages.push({ role: 'user', content: toolResults })
    if (done) break
  }

  return { fixResult, flagResult }
}

// ─── Process one Sentry issue ─────────────────────────────────────────────────

async function processIssue(issue, openAIPRs) {
  console.log(`\n── Issue [${issue.id}] ${issue.title}`)

  // Skip if we already have an open AI PR mentioning this issue
  if (openAIPRs.some(pr => pr.body?.includes(issue.id) || pr.body?.includes(issue.title))) {
    console.log('  Skipping — open AI PR already exists')
    return
  }

  let event
  try {
    event = await fetchLatestEvent(issue.id)
  } catch (e) {
    console.log(`  Cannot fetch event: ${e.message}`)
    return
  }

  const { fixResult, flagResult } = await runAgent(issue, event)

  if (!fixResult && !flagResult) {
    console.log('  No decision — skipping')
    return
  }

  if (fixResult) {
    const { confidence, fix_description, reasoning, files } = fixResult

    if (confidence >= CONFIDENCE_THRESHOLD) {
      // Create branch → commit files → open PR
      const branch = `ai-fix/sentry-${issue.id}-${Date.now()}`
      const baseSha = await getMainSha()
      await createBranch(branch, baseSha)

      for (const file of files) {
        await upsertFile(file.path, file.content, branch, `fix: ${fix_description}`)
        console.log(`  committed  ${file.path}`)
      }

      const pr = await createPR(issue, fixResult, branch)
      console.log(`  ✅ PR #${pr.number}: ${pr.html_url}`)
    } else if (confidence >= CONFIDENCE_ISSUE_MIN) {
      const gh = await createIssue(issue, fix_description, reasoning, confidence)
      console.log(`  ⚠️  Issue #${gh.number}: ${gh.html_url}`)
    } else {
      console.log(`  Confidence ${confidence} < ${CONFIDENCE_ISSUE_MIN} — skipping`)
    }
  } else if (flagResult) {
    const gh = await createIssue(
      issue,
      issue.title,
      `Claude could not auto-fix this issue.\n\n**Reason:** ${flagResult.reason}`,
      0,
    )
    console.log(`  ⚠️  Issue #${gh.number}: ${gh.html_url}`)
  }
}

// ─── Entry point ──────────────────────────────────────────────────────────────

async function main() {
  console.log('WorkForge AI Bug Fix Agent — starting')

  const required = ['ANTHROPIC_API_KEY', 'SENTRY_AUTH_TOKEN', 'SENTRY_DSN', 'GITHUB_TOKEN', 'REPO']
  const missing = required.filter(k => !process.env[k])
  if (missing.length) {
    console.error(`Missing env vars: ${missing.join(', ')}`)
    process.exit(1)
  }

  // Discover Sentry org + project slugs from DSN
  const { orgId, projectId } = parseDsn(process.env.SENTRY_DSN)
  console.log(`Sentry org ID: ${orgId}, project ID: ${projectId}`)

  let orgSlug, projectSlug
  try {
    ;({ orgSlug, projectSlug } = await discoverSentrySlugs(orgId, projectId))
    console.log(`Sentry: ${orgSlug}/${projectSlug}`)
  } catch (e) {
    console.error(`Sentry discovery failed: ${e.message}`)
    process.exit(1)
  }

  const issues = await fetchIssues(orgSlug, projectSlug)
  if (!issues.length) {
    console.log('No unresolved Sentry issues — all clear ✅')
    return
  }
  console.log(`Found ${issues.length} unresolved issue(s)`)

  const openAIPRs = await getOpenAIPRs()
  console.log(`Open AI PRs: ${openAIPRs.length}`)

  for (const issue of issues.slice(0, MAX_ISSUES)) {
    try {
      await processIssue(issue, openAIPRs)
    } catch (e) {
      console.error(`Error on issue ${issue.id}: ${e.message}`)
    }
  }

  console.log('\nAgent run complete.')
}

main().catch(e => {
  console.error('Fatal:', e)
  process.exit(1)
})
